[package]
name = "zedb-ch"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zedb-core.workspace = true
chrono.workspace = true
reqwest.workspace = true
dirs = "6"
regex = "1"
serde_json = "1"
tempfile = "3"
futures-util.workspace = true
tokio = { workspace = true, features = ["io-util", "io-std", "net", "fs"] }
thiserror.workspace = true
arc-swap = "1"
serde = { version = "1", features = ["derive"] }
klickhouse = { version = "0.15", default-features = false, features = ["tls", "compression"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
rustls-native-certs = "0.8"
tokio-rustls = { version = "0.26", default-features = false, features = ["ring"] }
rustls-pki-types = "1"
sha2 = "0.10"
flate2 = "1"
tar = "0.4"
libc = "0.2"

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
