[package]
name = "zedb-ch"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zedb-core.workspace = true
chrono.workspace = true
reqwest.workspace = true
dirs = "6"
futures-util.workspace = true
tokio.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
