//! The static completion vocabulary: SQL keywords and the common
//! ClickHouse functions. Curated rather than exhaustive (the server
//! knows ~1500 functions); these are the ones a person reaches for
//! while typing, each with a one-glance signature.

pub(super) const KEYWORDS: &[&str] = &[
    "SELECT",
    "FROM",
    "WHERE",
    "PREWHERE",
    "GROUP BY",
    "ORDER BY",
    "HAVING",
    "LIMIT",
    "LIMIT BY",
    "OFFSET",
    "JOIN",
    "LEFT JOIN",
    "RIGHT JOIN",
    "INNER JOIN",
    "FULL JOIN",
    "CROSS JOIN",
    "ARRAY JOIN",
    "LEFT ARRAY JOIN",
    "ON",
    "USING",
    "AS",
    "AND",
    "OR",
    "NOT",
    "IN",
    "LIKE",
    "ILIKE",
    "BETWEEN",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "DISTINCT",
    "UNION ALL",
    "WITH",
    "SAMPLE",
    "FINAL",
    "FORMAT",
    "SETTINGS",
    "INTERVAL",
    "ASC",
    "DESC",
    "NULLS FIRST",
    "NULLS LAST",
    "INSERT INTO",
    "VALUES",
    "CREATE TABLE",
    "CREATE VIEW",
    "CREATE MATERIALIZED VIEW",
    "ALTER TABLE",
    "DROP TABLE",
    "TRUNCATE TABLE",
    "RENAME TABLE",
    "DESCRIBE",
    "SHOW TABLES",
    "SHOW DATABASES",
    "SHOW CREATE TABLE",
    "EXPLAIN",
    "OPTIMIZE TABLE",
    "ENGINE",
    "PARTITION BY",
    "PRIMARY KEY",
    "TTL",
];

/// Types valid after the colon of a `{name:Type}` query parameter, in
/// priority order (the list order is preserved in the menu; the common
/// ones come first).
pub(super) const PARAM_TYPES: &[(&str, &str)] = &[
    ("Identifier", "database / table / column name"),
    ("String", ""),
    ("UInt64", ""),
    ("Int64", ""),
    ("Float64", ""),
    ("Bool", ""),
    ("Date", ""),
    ("Date32", ""),
    ("DateTime", ""),
    ("DateTime64(3)", ""),
    ("UUID", ""),
    ("UInt8", ""),
    ("UInt16", ""),
    ("UInt32", ""),
    ("Int8", ""),
    ("Int16", ""),
    ("Int32", ""),
    ("Float32", ""),
    ("IPv4", ""),
    ("IPv6", ""),
    ("Array(String)", ""),
    ("Array(UInt64)", ""),
    ("Array(Int64)", ""),
    ("Map(String, String)", ""),
];

pub(super) const FUNCTIONS: &[(&str, &str)] = &[
    // Aggregates.
    ("count", "count()"),
    ("countIf", "countIf(cond)"),
    ("countDistinct", "countDistinct(x)"),
    ("sum", "sum(x)"),
    ("sumIf", "sumIf(x, cond)"),
    ("avg", "avg(x)"),
    ("avgIf", "avgIf(x, cond)"),
    ("min", "min(x)"),
    ("max", "max(x)"),
    ("any", "any(x)"),
    ("anyLast", "anyLast(x)"),
    ("argMin", "argMin(arg, val)"),
    ("argMax", "argMax(arg, val)"),
    ("uniq", "uniq(x), approximate"),
    ("uniqExact", "uniqExact(x)"),
    ("quantile", "quantile(level)(x)"),
    ("quantiles", "quantiles(l1, l2, ...)(x)"),
    ("median", "median(x)"),
    ("groupArray", "groupArray(x)"),
    ("groupUniqArray", "groupUniqArray(x)"),
    ("topK", "topK(k)(x)"),
    ("stddevPop", "stddevPop(x)"),
    ("varPop", "varPop(x)"),
    ("corr", "corr(x, y)"),
    // Dates and times.
    ("now", "now()"),
    ("now64", "now64(precision)"),
    ("today", "today()"),
    ("yesterday", "yesterday()"),
    ("toDate", "toDate(x)"),
    ("toDateTime", "toDateTime(x)"),
    ("toDateTime64", "toDateTime64(x, precision)"),
    ("toStartOfMinute", "toStartOfMinute(t)"),
    ("toStartOfHour", "toStartOfHour(t)"),
    ("toStartOfDay", "toStartOfDay(t)"),
    ("toStartOfWeek", "toStartOfWeek(t)"),
    ("toStartOfMonth", "toStartOfMonth(t)"),
    ("toStartOfQuarter", "toStartOfQuarter(t)"),
    ("toStartOfYear", "toStartOfYear(t)"),
    ("toStartOfInterval", "toStartOfInterval(t, INTERVAL n unit)"),
    ("toYYYYMM", "toYYYYMM(t)"),
    ("toYYYYMMDD", "toYYYYMMDD(t)"),
    ("toYear", "toYear(t)"),
    ("toMonth", "toMonth(t)"),
    ("toDayOfMonth", "toDayOfMonth(t)"),
    ("toDayOfWeek", "toDayOfWeek(t)"),
    ("toHour", "toHour(t)"),
    ("toMinute", "toMinute(t)"),
    ("dateDiff", "dateDiff(unit, start, end)"),
    ("dateAdd", "dateAdd(unit, n, t)"),
    ("dateSub", "dateSub(unit, n, t)"),
    ("addDays", "addDays(t, n)"),
    ("subtractDays", "subtractDays(t, n)"),
    ("formatDateTime", "formatDateTime(t, format)"),
    ("toUnixTimestamp", "toUnixTimestamp(t)"),
    ("fromUnixTimestamp", "fromUnixTimestamp(n)"),
    ("toTimeZone", "toTimeZone(t, tz)"),
    // Conversions and null handling.
    ("toString", "toString(x)"),
    ("toInt32", "toInt32(x)"),
    ("toInt64", "toInt64(x)"),
    ("toUInt32", "toUInt32(x)"),
    ("toUInt64", "toUInt64(x)"),
    ("toFloat64", "toFloat64(x)"),
    ("toDecimal64", "toDecimal64(x, scale)"),
    ("CAST", "CAST(x AS Type)"),
    ("coalesce", "coalesce(a, b, ...)"),
    ("ifNull", "ifNull(x, alt)"),
    ("nullIf", "nullIf(x, y)"),
    ("isNull", "isNull(x)"),
    ("isNotNull", "isNotNull(x)"),
    ("assumeNotNull", "assumeNotNull(x)"),
    ("toNullable", "toNullable(x)"),
    // Conditionals and math.
    ("if", "if(cond, then, else)"),
    ("multiIf", "multiIf(cond1, then1, ..., else)"),
    ("greatest", "greatest(a, b, ...)"),
    ("least", "least(a, b, ...)"),
    ("abs", "abs(x)"),
    ("round", "round(x, n)"),
    ("floor", "floor(x)"),
    ("ceil", "ceil(x)"),
    ("intDiv", "intDiv(a, b)"),
    ("modulo", "modulo(a, b)"),
    // Strings.
    ("length", "length(s)"),
    ("empty", "empty(s)"),
    ("notEmpty", "notEmpty(s)"),
    ("lower", "lower(s)"),
    ("upper", "upper(s)"),
    ("lowerUTF8", "lowerUTF8(s)"),
    ("upperUTF8", "upperUTF8(s)"),
    ("substring", "substring(s, offset, length)"),
    ("trim", "trim(s)"),
    ("concat", "concat(a, b, ...)"),
    ("splitByChar", "splitByChar(sep, s)"),
    ("splitByString", "splitByString(sep, s)"),
    ("replaceOne", "replaceOne(s, pattern, replacement)"),
    ("replaceAll", "replaceAll(s, pattern, replacement)"),
    (
        "replaceRegexpAll",
        "replaceRegexpAll(s, regexp, replacement)",
    ),
    ("position", "position(haystack, needle)"),
    ("match", "match(s, regexp)"),
    ("extract", "extract(s, regexp)"),
    ("extractAll", "extractAll(s, regexp)"),
    ("startsWith", "startsWith(s, prefix)"),
    ("endsWith", "endsWith(s, suffix)"),
    ("formatReadableSize", "formatReadableSize(bytes)"),
    ("formatReadableQuantity", "formatReadableQuantity(n)"),
    // Arrays.
    ("arrayJoin", "arrayJoin(arr), one row per element"),
    ("array", "array(a, b, ...)"),
    ("arrayMap", "arrayMap(x -> expr, arr)"),
    ("arrayFilter", "arrayFilter(x -> cond, arr)"),
    ("arrayExists", "arrayExists(x -> cond, arr)"),
    ("arrayAll", "arrayAll(x -> cond, arr)"),
    ("arraySum", "arraySum(arr)"),
    ("arrayCount", "arrayCount(x -> cond, arr)"),
    ("arrayDistinct", "arrayDistinct(arr)"),
    ("arraySort", "arraySort(arr)"),
    ("arrayConcat", "arrayConcat(a, b, ...)"),
    ("arrayFlatten", "arrayFlatten(arr)"),
    ("arraySlice", "arraySlice(arr, offset, length)"),
    ("arrayStringConcat", "arrayStringConcat(arr, sep)"),
    ("has", "has(arr, elem)"),
    ("hasAll", "hasAll(arr, subset)"),
    ("hasAny", "hasAny(arr, other)"),
    ("indexOf", "indexOf(arr, elem)"),
    ("range", "range(n)"),
    // Tuples and maps.
    ("tuple", "tuple(a, b, ...)"),
    ("tupleElement", "tupleElement(t, n)"),
    ("mapKeys", "mapKeys(m)"),
    ("mapValues", "mapValues(m)"),
    // JSON.
    ("JSONExtract", "JSONExtract(json, key, 'Type')"),
    ("JSONExtractString", "JSONExtractString(json, key)"),
    ("JSONExtractInt", "JSONExtractInt(json, key)"),
    ("JSONExtractFloat", "JSONExtractFloat(json, key)"),
    ("JSONExtractBool", "JSONExtractBool(json, key)"),
    ("JSONExtractArrayRaw", "JSONExtractArrayRaw(json, key)"),
    ("JSONHas", "JSONHas(json, key)"),
    ("isValidJSON", "isValidJSON(s)"),
    // Hashes, UUIDs, randomness.
    ("cityHash64", "cityHash64(x, ...)"),
    ("sipHash64", "sipHash64(x, ...)"),
    ("xxHash64", "xxHash64(x)"),
    ("MD5", "MD5(s)"),
    ("SHA256", "SHA256(s)"),
    ("generateUUIDv4", "generateUUIDv4()"),
    ("toUUID", "toUUID(s)"),
    ("rand", "rand()"),
    // Window functions.
    ("row_number", "row_number() OVER (...)"),
    ("rank", "rank() OVER (...)"),
    ("dense_rank", "dense_rank() OVER (...)"),
    ("first_value", "first_value(x) OVER (...)"),
    ("last_value", "last_value(x) OVER (...)"),
    ("lagInFrame", "lagInFrame(x, n) OVER (...)"),
    ("leadInFrame", "leadInFrame(x, n) OVER (...)"),
    // Dictionaries.
    ("dictGet", "dictGet(dict, attr, key)"),
    (
        "dictGetOrDefault",
        "dictGetOrDefault(dict, attr, key, default)",
    ),
    ("dictHas", "dictHas(dict, key)"),
];
